<?php

/**
 * @file
 * Provides a student entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\student_module\Entity\Student;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function student_module_theme() {
  return [
    'student' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for student templates.
 *
 * Default template: student.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the student information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_student(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function student_module_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_reassign':
      // Anonymize students.
      $storage = \Drupal::entityTypeManager()->getStorage('student');
      $student_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($student_ids) as $student) {
        $student->setOwnerId(0);
        $student->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function student_module_user_predelete(UserInterface $account) {
  // Delete students.
  $storage = \Drupal::entityTypeManager()->getStorage('student');
  $student_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $students = $storage->loadMultiple($student_ids);
  $storage->delete($students);
}
